import Resolver from '@forge/resolver';
import api, { route } from '@forge/api';
import ExcelJS from 'exceljs';

const resolver = new Resolver();

async function listServiceDesks() {
  const response = await api.asApp().requestJira(
    route`/rest/servicedeskapi/servicedesk?limit=100`,
    { headers: { Accept: 'application/json' } }
  );
  if (!response.ok) throw new Error(`Could not list service projects (${response.status}).`);
  return (await response.json()).values || [];
}

async function findCustomer(serviceDeskId, query) {
  const response = await api.asApp().requestJira(
    route`/rest/servicedeskapi/servicedesk/${serviceDeskId}/customer?query=${query}&start=0&limit=100`,
    { headers: { Accept: 'application/json', 'X-ExperimentalApi': 'opt-in' } }
  );
  if (!response.ok) throw new Error(`Could not search portal customers (${response.status}).`);
  const values = (await response.json()).values || [];
  const needle = String(query || '').trim().toLowerCase();
  return values.find(u => String(u.emailAddress || '').toLowerCase() === needle)
    || values.find(u => String(u.displayName || '').toLowerCase().includes(needle))
    || values[0]
    || null;
}

async function listRequestTypes(serviceDeskId) {
  const response = await api.asApp().requestJira(
    route`/rest/servicedeskapi/servicedesk/${serviceDeskId}/requesttype?start=0&limit=100`,
    { headers: { Accept: 'application/json' } }
  );
  if (!response.ok) throw new Error(`Could not list request types (${response.status}).`);
  return (await response.json()).values || [];
}

async function requestTypeFields(serviceDeskId, requestTypeId) {
  const response = await api.asApp().requestJira(
    route`/rest/servicedeskapi/servicedesk/${serviceDeskId}/requesttype/${requestTypeId}/field`,
    { headers: { Accept: 'application/json' } }
  );
  if (!response.ok) return null;
  return await response.json();
}

async function chooseSimpleRequestType(serviceDeskId) {
  const types = await listRequestTypes(serviceDeskId);
  for (const type of types) {
    const meta = await requestTypeFields(serviceDeskId, type.id);
    const fields = meta?.requestTypeFields || [];
    const unsupportedRequired = fields.filter(f => f.required && !['summary', 'description'].includes(String(f.fieldId || '')));
    if (!unsupportedRequired.length) return { type, fields };
  }
  return types.length ? { type: types[0], fields: [] } : null;
}

async function createRequest(serviceDeskId, requestTypeId, customerAccountId) {
  const summary = `[Nuvriqo Report POC] Published Excel ${new Date().toISOString()}`;
  const body = {
    serviceDeskId: String(serviceDeskId),
    requestTypeId: String(requestTypeId),
    requestFieldValues: {
      summary,
      description: 'This request was created by the Nuvriqo Atlassian-only Portal Reports proof of concept.'
    },
    raiseOnBehalfOf: customerAccountId
  };

  const response = await api.asApp().requestJira(
    route`/rest/servicedeskapi/request`,
    {
      method: 'POST',
      headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    }
  );
  const raw = await response.text();
  let data = {};
  try { data = raw ? JSON.parse(raw) : {}; } catch {}
  if (!response.ok) throw new Error(`Could not create customer request (${response.status}): ${data?.errorMessage || data?.message || raw.slice(0, 240)}`);
  return data;
}

async function buildWorkbook() {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('Published Report');
  ws.columns = [
    { header: 'Source', key: 'source', width: 26 },
    { header: 'Value', key: 'value', width: 62 }
  ];
  ws.addRow({ source: 'POC', value: 'This Excel file was generated by a Forge backend using app permissions.' });
  ws.addRow({ source: 'Published', value: new Date().toISOString() });
  ws.addRow({ source: 'Purpose', value: 'Prove internal/backend-generated data can be deliberately published to a portal customer without giving access to source Jira issues.' });
  ws.getRow(1).font = { bold: true };
  return Buffer.from(await wb.xlsx.writeBuffer());
}

async function uploadTemporary(serviceDeskId, buffer, filename) {
  const form = new FormData();
  form.append(
    'file',
    new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
    filename
  );

  const response = await api.asApp().requestJira(
    route`/rest/servicedeskapi/servicedesk/${serviceDeskId}/attachTemporaryFile`,
    {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'X-Atlassian-Token': 'no-check',
        'X-ExperimentalApi': 'opt-in'
      },
      body: form
    }
  );
  const raw = await response.text();
  let data = {};
  try { data = raw ? JSON.parse(raw) : {}; } catch {}
  if (!response.ok) throw new Error(`Could not upload temporary attachment (${response.status}): ${raw.slice(0, 240)}`);
  const item = data?.temporaryAttachments?.[0];
  if (!item?.temporaryAttachmentId) throw new Error('Temporary attachment upload returned no attachment ID.');
  return item;
}

async function publishAttachment(issueKey, temporaryAttachmentId) {
  const response = await api.asApp().requestJira(
    route`/rest/servicedeskapi/request/${issueKey}/attachment`,
    {
      method: 'POST',
      headers: { Accept: 'application/json', 'Content-Type': 'application/json' },
      body: JSON.stringify({
        public: true,
        temporaryAttachmentIds: [temporaryAttachmentId],
        additionalComment: {
          body: 'Your published Nuvriqo Excel report is attached.'
        }
      })
    }
  );
  const raw = await response.text();
  let data = {};
  try { data = raw ? JSON.parse(raw) : {}; } catch {}
  if (!response.ok) throw new Error(`Could not publish attachment (${response.status}): ${data?.errorMessage || data?.message || raw.slice(0, 240)}`);
  return data;
}

resolver.define('poc:service-desks', async () => {
  const desks = await listServiceDesks();
  return desks.map(d => ({ id: d.id, projectId: d.projectId, projectName: d.projectName, projectKey: d.projectKey || '' }));
});

resolver.define('poc:publish', async ({ payload }) => {
  const email = String(payload?.email || '').trim();
  const serviceDeskId = String(payload?.serviceDeskId || '').trim();
  if (!email) throw new Error('Enter the portal customer email address.');
  if (!serviceDeskId) throw new Error('Choose a service project.');

  const customer = await findCustomer(serviceDeskId, email);
  if (!customer?.accountId) throw new Error('No matching portal customer was found in that service project.');

  const selected = await chooseSimpleRequestType(serviceDeskId);
  if (!selected?.type?.id) throw new Error('No usable customer request type was found.');

  const request = await createRequest(serviceDeskId, selected.type.id, customer.accountId);
  const issueKey = request?.issueKey || request?.issueId;
  if (!issueKey) throw new Error('The customer request was created but no issue key was returned.');

  const filename = `nuvriqo-published-report-${Date.now()}.xlsx`;
  const workbook = await buildWorkbook();
  const temporary = await uploadTemporary(serviceDeskId, workbook, filename);
  const published = await publishAttachment(issueKey, temporary.temporaryAttachmentId);

  const attachmentPayload =
    Array.isArray(published?.attachments) ? published.attachments :
    Array.isArray(published?.values) ? published.values :
    published?.attachment ? [published.attachment] :
    published?.attachments && typeof published.attachments === 'object' ? Object.values(published.attachments) :
    [];

  return {
    ok: true,
    issueKey,
    customer: customer.displayName || customer.emailAddress || customer.accountId,
    requestType: selected.type.name || selected.type.id,
    filename,
    publishedAttachments: attachmentPayload.map(a => ({
      filename: a?.filename || filename,
      content: a?._links?.content || a?.content || ''
    }))
  };
});

export const handler = resolver.getDefinitions();
