import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke } from '@forge/bridge';
import './styles.css';

const downloadBase64=(base64,filename)=>{const b=atob(base64);const bytes=new Uint8Array(b.length);for(let i=0;i<b.length;i++)bytes[i]=b.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=filename||'jira-report.xlsx';a.click();URL.revokeObjectURL(url)};
const splitEmails=v=>v.split(',').map(x=>x.trim()).filter(Boolean);
const scheduleLabel=s=>{const t=s?.time||'08:00';if(s?.frequency==='daily')return `daily at ${t}`;if(s?.frequency==='weekdays')return `weekdays at ${t}`;if(s?.frequency==='monthly')return `monthly on day ${s.monthDay||1} at ${t}`;return `every ${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][s?.weekday??1]} at ${t}`};

function App(){
 const [reports,setReports]=useState([]),[editing,setEditing]=useState(null),[fields,setFields]=useState([]),[filters,setFilters]=useState([]),[notice,setNotice]=useState(''),[history,setHistory]=useState(null),[busy,setBusy]=useState(false);
 const refresh=()=>invoke('report:list').then(setReports);
 useEffect(()=>{refresh();invoke('jira:fields').then(setFields).catch(()=>{});invoke('jira:filters').then(setFilters).catch(()=>{})},[]);
 const create=async()=>setEditing(await invoke('report:new'));
 const save=async report=>{setBusy(true);try{await invoke('report:save',{report});setEditing(null);await refresh();setNotice('Report saved.')}finally{setBusy(false)}};
 const run=async r=>{setBusy(true);setNotice(`Generating ${r.name}…`);try{const x=await invoke('report:run',{id:r.id});downloadBase64(x.workbookBase64,`${r.name}.xlsx`);setNotice(`Generated ${x.entry.issueCount} issues.`)}catch(e){setNotice(e.message||'Report failed.')}finally{setBusy(false)}};
 const duplicate=async r=>{await invoke('report:duplicate',{id:r.id});await refresh();setNotice('Report duplicated.')};
 const remove=async r=>{if(!confirm(`Delete “${r.name}”?`))return;await invoke('report:delete',{id:r.id});await refresh()};
 const openHistory=async r=>setHistory({report:r,runs:await invoke('report:history',{id:r.id})});
 if(editing)return <Editor report={editing} setReport={setEditing} fields={fields} filters={filters} save={save} cancel={()=>setEditing(null)} busy={busy}/>;
 if(history)return <main><button className="link" onClick={()=>setHistory(null)}>← Reports</button><h1>{history.report.name}</h1><section className="panel"><h2>Run history</h2>{!history.runs?.length?<p>No runs recorded yet.</p>:history.runs.map(x=><div className="history" key={x.id}><strong>{x.status==='success'?'✓ Successful':'✕ Failed'}</strong><span>{new Date(x.at).toLocaleString()} {x.issueCount!=null?`· ${x.issueCount} issues`:''}</span>{x.message&&<small>{x.message}</small>}</div>)}</section></main>;
 return <main><header><div><div className="eyebrow">Nuvriqo</div><h1>Excel Report Manager</h1><p>Create, style, schedule and email Jira Excel reports without Automation rules.</p></div><button className="primary" onClick={create}>+ Create report</button></header>{notice&&<div className="notice">{notice}</div>}<section className="cards"><div className="stat"><strong>{reports.length}</strong><span>Reports</span></div><div className="stat"><strong>{reports.filter(r=>r.enabled).length}</strong><span>Active schedules</span></div><div className="stat"><strong>No rules</strong><span>Automation required</span></div></section><section className="panel"><h2>Your reports</h2>{!reports.length?<div className="empty"><h3>No reports yet</h3><p>Create your first Excel report.</p><button className="primary" onClick={create}>Create report</button></div>:reports.map(r=><div className="report" key={r.id}><div><strong>{r.name}</strong><small>{r.source?.jql||'No data source'}</small></div><span>{scheduleLabel(r.schedule)}</span><span className={r.enabled?'pill on':'pill'}>{r.enabled?'Active':'Draft'}</span><div className="actions"><button disabled={busy} onClick={()=>run(r)}>Run now</button><button onClick={()=>setEditing(r)}>Edit</button><button onClick={()=>openHistory(r)}>History</button><button onClick={()=>duplicate(r)}>Duplicate</button><button className="danger" onClick={()=>remove(r)}>Delete</button></div></div>)}</section></main>
}

function Editor({report,setReport,fields,filters,save,cancel,busy}){
 const [step,setStep]=useState(1),[previewing,setPreviewing]=useState(false),[message,setMessage]=useState('');
 const set=(path,value)=>{const n=structuredClone(report);let o=n;for(let i=0;i<path.length-1;i++){if(o[path[i]]==null)o[path[i]]={};o=o[path[i]]}o[path.at(-1)]=value;setReport(n)};
 const cols=report.template.columns,used=new Set(cols.map(c=>c.fieldId));
 const addField=e=>{const id=e.target.value;if(!id)return;const f=fields.find(x=>x.id===id);set(['template','columns'],[...cols,{fieldId:id,label:f?.name||id,width:20}]);e.target.value=''};
 const move=(i,d)=>{const n=[...cols],j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];set(['template','columns'],n)};
 const chooseFilter=e=>{const id=e.target.value,f=filters.find(x=>x.id===id);set(['source','filterId'],id||null);if(f?.jql)set(['source','jql'],f.jql)};
 const preview=async()=>{setPreviewing(true);try{const x=await invoke('report:preview',{report});downloadBase64(x.workbookBase64,`${report.name}-preview.xlsx`);setMessage(`Preview generated with ${x.entry.issueCount} issues.`)}catch(e){setMessage(e.message||'Preview failed.')}finally{setPreviewing(false)}};
 const names=['Data','Columns','Workbook','Schedule','Email'];
 return <main><header><div><button className="link" onClick={cancel}>← Reports</button><h1>{report.id?'Edit report':'Create report'}</h1><p>Build the report in five simple steps.</p></div><div className="actions"><button onClick={preview} disabled={previewing}>{previewing?'Generating…':'Download preview'}</button><button className="primary" disabled={busy} onClick={()=>save(report)}>Save report</button></div></header>{message&&<div className="notice">{message}</div>}<nav className="steps">{names.map((n,i)=><button className={step===i+1?'active':''} onClick={()=>setStep(i+1)} key={n}>{i+1}. {n}</button>)}</nav>
 {step===1&&<section className="panel"><h2>Report data</h2><div className="grid"><label>Report name<input value={report.name} onChange={e=>set(['name'],e.target.value)}/></label><label>Saved Jira filter<select value={report.source.filterId||''} onChange={chooseFilter}><option value="">None — use JQL</option>{filters.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div><label>JQL<textarea rows="5" value={report.source.jql} onChange={e=>set(['source','jql'],e.target.value)}/></label><label>Maximum issues<input className="smallInput" type="number" min="1" max="5000" value={report.source.maxIssues||500} onChange={e=>set(['source','maxIssues'],Number(e.target.value)||500)}/></label></section>}
 {step===2&&<section className="panel"><div className="sectionHead"><div><h2>Excel columns</h2><p>Add Jira fields, rename headings and set their order.</p></div><select onChange={addField} defaultValue=""><option value="">+ Add Jira field…</option>{fields.filter(f=>!used.has(f.id)).map(f=><option key={f.id} value={f.id}>{f.name}{f.custom?' · custom':''}</option>)}</select></div>{cols.map((c,i)=><div className="column" key={`${c.fieldId}-${i}`}><strong>{i+1}</strong><input value={c.label} onChange={e=>{const n=[...cols];n[i]={...c,label:e.target.value};set(['template','columns'],n)}}/><input type="number" min="8" max="80" value={c.width||20} onChange={e=>{const n=[...cols];n[i]={...c,width:Number(e.target.value)};set(['template','columns'],n)}}/><small>{c.fieldId}</small><div className="actions"><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><button className="danger" onClick={()=>set(['template','columns'],cols.filter((_,x)=>x!==i))}>×</button></div></div>)}</section>}
 {step===3&&<section className="panel"><h2>Workbook design</h2><div className="grid"><label>Worksheet name<input value={report.template.workbook.sheetName||'Issues'} onChange={e=>set(['template','workbook','sheetName'],e.target.value)}/></label><label>Report title<input value={report.template.workbook.title||''} onChange={e=>set(['template','workbook','title'],e.target.value)}/></label></div><label>Subtitle<input value={report.template.workbook.subtitle||''} onChange={e=>set(['template','workbook','subtitle'],e.target.value)}/></label><div className="checks">{[['freezeHeader','Freeze header'],['autoFilter','Excel filters'],['alternateRows','Alternating rows'],['jiraLinks','Jira links'],['generatedAt','Generated date']].map(([k,l])=><label key={k}><input type="checkbox" checked={report.template.workbook[k]!==false} onChange={e=>set(['template','workbook',k],e.target.checked)}/>{l}</label>)}</div></section>}
 {step===4&&<section className="panel"><h2>Schedule</h2><label className="check"><input type="checkbox" checked={report.enabled} onChange={e=>set(['enabled'],e.target.checked)}/>Enable scheduled delivery</label><div className="grid"><label>Frequency<select value={report.schedule.frequency} onChange={e=>set(['schedule','frequency'],e.target.value)}><option value="daily">Daily</option><option value="weekdays">Weekdays</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>Time<input type="time" value={report.schedule.time} onChange={e=>set(['schedule','time'],e.target.value)}/></label></div>{report.schedule.frequency==='weekly'&&<label>Day<select value={report.schedule.weekday??1} onChange={e=>set(['schedule','weekday'],Number(e.target.value))}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label>}{report.schedule.frequency==='monthly'&&<label>Day of month<input type="number" min="1" max="28" value={report.schedule.monthDay||1} onChange={e=>set(['schedule','monthDay'],Number(e.target.value))}/></label>}<label>Timezone<input value={report.schedule.timezone} onChange={e=>set(['schedule','timezone'],e.target.value)}/></label><div className="notice">This report will run {scheduleLabel(report.schedule)}.</div></section>}
 {step===5&&<section className="panel"><h2>Email delivery</h2><p>Configure the message here. Email transport is connected once at installation level.</p><label>To<input value={report.delivery.recipients.join(', ')} onChange={e=>set(['delivery','recipients'],splitEmails(e.target.value))}/></label><label>CC<input value={(report.delivery.cc||[]).join(', ')} onChange={e=>set(['delivery','cc'],splitEmails(e.target.value))}/></label><label>Subject<input value={report.delivery.subject} onChange={e=>set(['delivery','subject'],e.target.value)}/></label><label>Message<textarea rows="6" value={report.delivery.body} onChange={e=>set(['delivery','body'],e.target.value)}/></label><label>Attachment name<input value={report.delivery.attachmentName} onChange={e=>set(['delivery','attachmentName'],e.target.value)}/></label></section>}
 <footer><button disabled={step===1} onClick={()=>setStep(step-1)}>← Back</button><span>Step {step} of 5</span>{step<5?<button className="primary" onClick={()=>setStep(step+1)}>Next →</button>:<button className="primary" onClick={()=>save(report)}>Save report</button>}</footer></main>
}
createRoot(document.getElementById('root')).render(<App/>);
