import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke } from '@forge/bridge';
import './styles.css';

const downloadBase64=(base64,filename)=>{const b=atob(base64);const bytes=new Uint8Array(b.length);for(let i=0;i<b.length;i++)bytes[i]=b.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=filename||'jira-report.xlsx';a.click();URL.revokeObjectURL(url)};
const splitEmails=v=>v.split(',').map(x=>x.trim()).filter(Boolean);
const scheduleLabel=s=>{const t=s?.time||'08:00';if(s?.frequency==='daily')return `daily at ${t}`;if(s?.frequency==='weekdays')return `weekdays at ${t}`;if(s?.frequency==='monthly')return `monthly on day ${s.monthDay||1} at ${t}`;return `every ${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][s?.weekday??1]} at ${t}`};
const colour=(value,fallback)=>value||fallback;

function App(){
 const [reports,setReports]=useState([]),[editing,setEditing]=useState(null),[fields,setFields]=useState([]),[filters,setFilters]=useState([]),[notice,setNotice]=useState(''),[history,setHistory]=useState(null),[busy,setBusy]=useState(false),[emailSettings,setEmailSettings]=useState(null);
 const refresh=()=>invoke('report:list').then(setReports);
 useEffect(()=>{refresh();invoke('jira:fields').then(setFields).catch(()=>{});invoke('jira:filters').then(setFilters).catch(()=>{})},[]);
 const create=async()=>setEditing(await invoke('report:new'));
 const save=async report=>{setBusy(true);try{await invoke('report:save',{report});setEditing(null);await refresh();setNotice('Report saved.')}catch(e){setNotice(e.message||'Could not save report.')}finally{setBusy(false)}};
 const run=async r=>{setBusy(true);setNotice(`Generating ${r.name}…`);try{const x=await invoke('report:run',{id:r.id});downloadBase64(x.workbookBase64,`${r.name}.xlsx`);setNotice(`Generated ${x.entry.issueCount} issues.`)}catch(e){setNotice(e.message||'Report failed.')}finally{setBusy(false)}};
 const duplicate=async r=>{await invoke('report:duplicate',{id:r.id});await refresh();setNotice('Report duplicated.')};
 const remove=async r=>{if(!confirm(`Delete “${r.name}”?`))return;await invoke('report:delete',{id:r.id});await refresh()};
 const openHistory=async r=>setHistory({report:r,runs:await invoke('report:history',{id:r.id})});
 const openEmailSettings=async()=>{setBusy(true);try{setEmailSettings(await invoke('email:settings:get'))}catch(e){setNotice(e.message||'Could not load email settings.')}finally{setBusy(false)}};
 if(emailSettings)return <EmailSettings initial={emailSettings} close={()=>setEmailSettings(null)} notify={setNotice}/>;
 if(editing)return <Editor report={editing} setReport={setEditing} fields={fields} filters={filters} save={save} cancel={()=>setEditing(null)} busy={busy}/>;
 if(history)return <main><button className="link" onClick={()=>setHistory(null)}>← Reports</button><h1>{history.report.name}</h1><section className="panel"><h2>Run history</h2>{!history.runs?.length?<p>No runs recorded yet.</p>:history.runs.map(x=><div className="history" key={x.id}><strong>{x.status==='success'?'✓ Successful':'✕ Failed'}</strong><span>{new Date(x.at).toLocaleString()} {x.issueCount!=null?`· ${x.issueCount} issues`:''}</span>{x.message&&<small>{x.message}</small>}</div>)}</section></main>;
 return <main><header><div><div className="eyebrow">Nuvriqo</div><h1>Excel Report Manager</h1><p>Create, style, schedule and email Jira Excel reports without Automation rules.</p></div><div className="actions"><button onClick={openEmailSettings}>Email settings</button><button className="primary" onClick={create}>+ Create report</button></div></header>{notice&&<div className="notice">{notice}</div>}<section className="cards"><div className="stat"><strong>{reports.length}</strong><span>Reports</span></div><div className="stat"><strong>{reports.filter(r=>r.enabled).length}</strong><span>Active schedules</span></div><div className="stat"><strong>No rules</strong><span>Automation required</span></div></section><section className="panel"><h2>Your reports</h2>{!reports.length?<div className="empty"><h3>No reports yet</h3><p>Create your first Excel report.</p><button className="primary" onClick={create}>Create report</button></div>:reports.map(r=><div className="report" key={r.id}><div><strong>{r.name}</strong><small>{r.source?.jql||'No data source'}</small></div><span>{scheduleLabel(r.schedule)}</span><span className={r.enabled?'pill on':'pill'}>{r.enabled?'Active':'Draft'}</span><div className="actions"><button disabled={busy} onClick={()=>run(r)}>Run now</button><button onClick={()=>setEditing(r)}>Edit</button><button onClick={()=>openHistory(r)}>History</button><button onClick={()=>duplicate(r)}>Duplicate</button><button className="danger" onClick={()=>remove(r)}>Delete</button></div></div>)}</section></main>
}

function EmailSettings({initial,close,notify}){
 const [settings,setSettings]=useState({...initial,secret:''}),[saving,setSaving]=useState(false),[testAddress,setTestAddress]=useState(''),[message,setMessage]=useState('');
 const set=(key,value)=>setSettings(s=>({...s,[key]:value}));
 const save=async()=>{setSaving(true);try{const saved=await invoke('email:settings:save',{settings});setSettings({...saved,secret:''});setMessage('Email settings saved.');notify('Email settings saved.')}catch(e){setMessage(e.message||'Could not save email settings.')}finally{setSaving(false)}};
 const test=async()=>{setSaving(true);try{await invoke('email:test',{address:testAddress});setMessage(`Test email sent to ${testAddress}.`)}catch(e){setMessage(e.message||'Test email failed.')}finally{setSaving(false)}};
 return <main><header><div><button className="link" onClick={close}>← Reports</button><div className="eyebrow">Delivery</div><h1>Email settings</h1><p>Connect one mail provider for all scheduled reports on this Jira site.</p></div><button className="primary" disabled={saving} onClick={save}>{saving?'Saving…':'Save settings'}</button></header>{message&&<div className="notice">{message}</div>}<section className="panel"><h2>Provider</h2><label>Email provider<select value={settings.provider||'none'} onChange={e=>set('provider',e.target.value)}><option value="none">Not configured</option><option value="microsoft-graph">Microsoft 365 / Graph</option><option value="sendgrid">SendGrid</option></select></label>{settings.provider!=='none'&&<><div className="grid"><label>Sender email<input type="email" value={settings.senderEmail||''} onChange={e=>set('senderEmail',e.target.value)} placeholder="reports@company.com"/></label><label>Sender name<input value={settings.senderName||''} onChange={e=>set('senderName',e.target.value)} placeholder="Jira Reports"/></label></div>{settings.provider==='microsoft-graph'&&<div className="grid"><label>Microsoft tenant ID<input value={settings.tenantId||''} onChange={e=>set('tenantId',e.target.value)}/></label><label>Application / client ID<input value={settings.clientId||''} onChange={e=>set('clientId',e.target.value)}/></label></div>}<label>{settings.provider==='microsoft-graph'?'Client secret':'SendGrid API key'}<input type="password" value={settings.secret||''} onChange={e=>set('secret',e.target.value)} placeholder={settings.hasSecret?'Saved securely — leave blank to keep it':'Enter secret'}/><small>{settings.hasSecret?'A credential is already stored securely. Enter a new one only to replace it.':'No credential stored yet.'}</small></label></>}</section>{settings.provider!=='none'&&<section className="panel"><h2>Test delivery</h2><p>Save the provider settings first, then send a quick test before enabling scheduled reports.</p><div className="grid"><label>Test recipient<input type="email" value={testAddress} onChange={e=>setTestAddress(e.target.value)} placeholder="you@company.com"/></label><div className="fieldButton"><button disabled={saving||!testAddress} onClick={test}>Send test email</button></div></div></section>}</main>
}

function Editor({report,setReport,fields,filters,save,cancel,busy}){
 const [step,setStep]=useState(1),[previewing,setPreviewing]=useState(false),[message,setMessage]=useState('');
 const set=(path,value)=>{const n=structuredClone(report);let o=n;for(let i=0;i<path.length-1;i++){if(o[path[i]]==null)o[path[i]]={};o=o[path[i]]}o[path.at(-1)]=value;setReport(n)};
 const cols=report.template.columns,used=new Set(cols.map(c=>c.fieldId)),wb=report.template.workbook||{};
 const addField=e=>{const id=e.target.value;if(!id)return;const f=fields.find(x=>x.id===id);set(['template','columns'],[...cols,{fieldId:id,label:f?.name||id,width:20}]);e.target.value=''};
 const move=(i,d)=>{const n=[...cols],j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];set(['template','columns'],n)};
 const chooseFilter=e=>{const id=e.target.value,f=filters.find(x=>x.id===id);set(['source','filterId'],id||null);set(['source','type'],id?'filter':'jql');if(f?.jql)set(['source','jql'],f.jql)};
 const preview=async()=>{setPreviewing(true);try{const x=await invoke('report:preview',{report});downloadBase64(x.workbookBase64,`${report.name}-preview.xlsx`);setMessage(`Preview generated with ${x.entry.issueCount} issues.`)}catch(e){setMessage(e.message||'Preview failed.')}finally{setPreviewing(false)}};
 const names=['Data','Columns','Workbook','Schedule','Email'];
 return <main><header><div><button className="link" onClick={cancel}>← Reports</button><h1>{report.id?'Edit report':'Create report'}</h1><p>Build the report in five simple steps.</p></div><div className="actions"><button onClick={preview} disabled={previewing}>{previewing?'Generating…':'Download preview'}</button><button className="primary" disabled={busy} onClick={()=>save(report)}>Save report</button></div></header>{message&&<div className="notice">{message}</div>}<nav className="steps">{names.map((n,i)=><button className={step===i+1?'active':''} onClick={()=>setStep(i+1)} key={n}>{i+1}. {n}</button>)}</nav>
 {step===1&&<section className="panel"><h2>Report data</h2><div className="grid"><label>Report name<input value={report.name} onChange={e=>set(['name'],e.target.value)}/></label><label>Saved Jira filter<select value={report.source.filterId||''} onChange={chooseFilter}><option value="">None — use JQL</option>{filters.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div><label>JQL<textarea rows="5" value={report.source.jql} onChange={e=>set(['source','jql'],e.target.value)}/></label><label>Maximum issues<input className="smallInput" type="number" min="1" max="5000" value={report.source.maxIssues||500} onChange={e=>set(['source','maxIssues'],Number(e.target.value)||500)}/></label></section>}
 {step===2&&<section className="panel"><div className="sectionHead"><div><h2>Excel columns</h2><p>Add Jira fields, rename headings and set their order.</p></div><select onChange={addField} defaultValue=""><option value="">+ Add Jira field…</option>{fields.filter(f=>!used.has(f.id)).map(f=><option key={f.id} value={f.id}>{f.name}{f.custom?' · custom':''}</option>)}</select></div>{cols.map((c,i)=><div className="column" key={`${c.fieldId}-${i}`}><strong>{i+1}</strong><input value={c.label} onChange={e=>{const n=[...cols];n[i]={...c,label:e.target.value};set(['template','columns'],n)}}/><input type="number" min="8" max="80" value={c.width||20} onChange={e=>{const n=[...cols];n[i]={...c,width:Number(e.target.value)};set(['template','columns'],n)}}/><small>{c.fieldId}</small><div className="actions"><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><button className="danger" onClick={()=>set(['template','columns'],cols.filter((_,x)=>x!==i))}>×</button></div></div>)}</section>}
 {step===3&&<section className="panel"><h2>Workbook design</h2><p>Style the Excel workbook here. Report details are placed below the final data row.</p><div className="grid"><label>Worksheet name<input value={wb.sheetName||'Issues'} onChange={e=>set(['template','workbook','sheetName'],e.target.value)}/></label><label>Report title<input value={wb.title||''} onChange={e=>set(['template','workbook','title'],e.target.value)} placeholder={report.name}/></label></div><label>Subtitle<input value={wb.subtitle||''} onChange={e=>set(['template','workbook','subtitle'],e.target.value)}/></label><h3>Header styling</h3><div className="styleGrid"><label>Header background<input type="color" value={colour(wb.headerBackground,'#0C66E4')} onChange={e=>set(['template','workbook','headerBackground'],e.target.value)}/></label><label>Header text<input type="color" value={colour(wb.headerTextColor,'#FFFFFF')} onChange={e=>set(['template','workbook','headerTextColor'],e.target.value)}/></label><label>Font<select value={wb.fontName||'Aptos'} onChange={e=>set(['template','workbook','fontName'],e.target.value)}><option>Aptos</option><option>Arial</option><option>Calibri</option><option>Verdana</option><option>Tahoma</option><option>Times New Roman</option></select></label><label>Header size<input type="number" min="8" max="24" value={wb.headerFontSize||11} onChange={e=>set(['template','workbook','headerFontSize'],Number(e.target.value)||11)}/></label><label>Header alignment<select value={wb.headerAlignment||'left'} onChange={e=>set(['template','workbook','headerAlignment'],e.target.value)}><option value="left">Left</option><option value="center">Centre</option><option value="right">Right</option></select></label><label>Row height<input type="number" min="14" max="40" value={wb.rowHeight||20} onChange={e=>set(['template','workbook','rowHeight'],Number(e.target.value)||20)}/></label></div><h3>Body styling</h3><div className="styleGrid"><label>Body text<input type="color" value={colour(wb.bodyTextColor,'#172B4D')} onChange={e=>set(['template','workbook','bodyTextColor'],e.target.value)}/></label><label>Alternate row colour<input type="color" value={colour(wb.alternateRowBackground,'#F7F8F9')} onChange={e=>set(['template','workbook','alternateRowBackground'],e.target.value)}/></label><label>Body font size<input type="number" min="8" max="18" value={wb.bodyFontSize||11} onChange={e=>set(['template','workbook','bodyFontSize'],Number(e.target.value)||11)}/></label></div><div className="checks">{[['headerBold','Bold headings'],['freezeHeader','Freeze header'],['autoFilter','Excel filters'],['alternateRows','Alternating rows'],['jiraLinks','Jira links'],['footerInfo','Report details below data'],['generatedAt','Generated date']].map(([k,l])=><label key={k}><input type="checkbox" checked={wb[k]!==false} onChange={e=>set(['template','workbook',k],e.target.checked)}/>{l}</label>)}</div></section>}
 {step===4&&<section className="panel"><h2>Schedule</h2><label className="check"><input type="checkbox" checked={report.enabled} onChange={e=>set(['enabled'],e.target.checked)}/>Enable scheduled delivery</label><div className="grid"><label>Frequency<select value={report.schedule.frequency} onChange={e=>set(['schedule','frequency'],e.target.value)}><option value="daily">Daily</option><option value="weekdays">Weekdays</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>Time<input type="time" value={report.schedule.time} onChange={e=>set(['schedule','time'],e.target.value)}/></label></div>{report.schedule.frequency==='weekly'&&<label>Day<select value={report.schedule.weekday??1} onChange={e=>set(['schedule','weekday'],Number(e.target.value))}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label>}{report.schedule.frequency==='monthly'&&<label>Day of month<input type="number" min="1" max="28" value={report.schedule.monthDay||1} onChange={e=>set(['schedule','monthDay'],Number(e.target.value))}/></label>}<label>Timezone<input value={report.schedule.timezone} onChange={e=>set(['schedule','timezone'],e.target.value)}/></label><div className="notice">This report will run {scheduleLabel(report.schedule)}.</div></section>}
 {step===5&&<section className="panel"><h2>Email delivery</h2><p>Configure the message here. The mail provider is connected once in Email settings.</p><label>To<input value={report.delivery.recipients.join(', ')} onChange={e=>set(['delivery','recipients'],splitEmails(e.target.value))}/></label><label>CC<input value={(report.delivery.cc||[]).join(', ')} onChange={e=>set(['delivery','cc'],splitEmails(e.target.value))}/></label><label>Subject<input value={report.delivery.subject} onChange={e=>set(['delivery','subject'],e.target.value)}/></label><label>Message<textarea rows="6" value={report.delivery.body} onChange={e=>set(['delivery','body'],e.target.value)}/></label><label>Attachment name<input value={report.delivery.attachmentName} onChange={e=>set(['delivery','attachmentName'],e.target.value)}/></label></section>}
 <footer><button disabled={step===1} onClick={()=>setStep(step-1)}>← Back</button><span>Step {step} of 5</span>{step<5?<button className="primary" onClick={()=>setStep(step+1)}>Next →</button>:<button className="primary" onClick={()=>save(report)}>Save report</button>}</footer></main>
}

createRoot(document.getElementById('root')).render(<App/>);
